version: "3"

services:
  nestjs:
    image: node:22-alpine # Bạn có thể thay thế bằng phiên bản Node.js mà bạn cần
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app # Gắn kết thư mục hiện tại với thư mục trong container
      - /usr/src/app/node_modules # Đảm bảo không ghi đè thư mục node_modules
    ports:
      - "4000:4000"
      - "5001:5001"
      - "5000:5000"
    command: sh -c "npm install && npm run dev"

volumes:
  mongo-data:
    driver: local
